name: 'Setup o3de, o3de-extras and ros2 env'
description: 'Install system depends required to run'
author: 'Robotec.AI'
inputs:
  use-ros2-testing:
    description: |
      Enable use of the ROS2 pre-release testing debs.
    required: false
    default: "false"
  install-connext:
    description: |
      Install RTI Connext (and by default accept non-commercial license).
    required: false
    default: "false"
  required-ros-distributions:
    description: | 
    "foxy humble rolling".
    required: false
    default: "foxy humble rolling"
runs:
  using: "node16"
  main: "dist/index.js"